-- return {
--   dir = "~/code/nvim/pomo.nvim",
--   name = "pomo",
--   config = function()
--     require("pomo").setup()
--   end,
-- }

return {
  -- -- Use a local development path instead of the GitHub repository
  -- dir = "~/code/nvim/pomo.nvim", -- Replace this with the path to your dev dir
  -- dependencies = { "nvim-lua/plenary.nvim" }, -- plenary for tests
  -- config = function()
  --   require("pomo").setup() -- Use the default
  --   -- Or use this if you would like custom configuration
  --   -- config = function()
  --   --   require("chkn").setup({
  --   --     width = 80,
  --   --     height = 20,
  --   --     border = "rounded",
  --   --     persistent = true,
  --   --   })
  -- end,
  -- lazy = false,
  -- debug = true,
  -- -- keys = {
  -- --   {
  -- --     "<leader>sp",
  -- --     function()
  -- --       vim.cmd("silent! ChknToggle")
  -- --     end,
  -- --     desc = "Toggle Scratchpad",
  -- --   },
  -- -- },
}
